version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  waferInfo:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/trainingPhase.log
loggers:
  Wafer:
    level: DEBUG
    handlers: [waferInfo]
    propagate: no
root:
  level: DEBUG
  handlers: [waferInfo]