version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
loggers:
  Wafer:
    level: DEBUG
    handlers: [info_file_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [info_file_handler]