

estimators:
  RandomForestClassifier:
    params:
      n_estimators: [ 50 ]
      criterion: [ 'gini']
      max_depth: [2, 3, 4]
      max_features: ['auto']

  XGBoostClassifier:
    params:
      learning_rate: [ 0.01, 0.001 ]
      max_depth: [ 5, 10 ]
      n_estimators: [ 10, 50 ]

reports:
  params: reports/params.json
  scores: reports/scores.json

